### PR TITLE
Added tldr summary

### PR DESCRIPTION
**Pull request by neozenith**

### CODE REVIEW

**Comment by neozenith** [comment]
@agentk and/or @cathylill if you have time to review.

**Comment by agentk** [comment]
To be honest, I'm not a fan of adding a TL;DR to a Code of Conduct. It's pretty short to start with, and more important that it's read than paraphrased.

If we do need a TL;DR section, can we use a term less gender specific? I'm a big fan of 'arse hat'.

**Comment by cathylill** [comment]
Agreed, we want people to read it all. Also good to avoid any suggestion that censure may be purely based on admins interpretation of a vague label like ' that guy '.

**Comment by neozenith** [comment]
Thanks for the review. This is why I made it a PR to get feedback.

I'll close this branch.

**Pull request closed without merging**
